# Generated by Django 3.1 on 2020-08-26 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('total_weight', models.IntegerField(default=0)),
                ('total_weight_format', models.CharField(choices=[('g', 'Grams'), ('Kg', 'Kilograms'), ('mL', 'Millilitre'), ('L', 'Litre')], default='g', max_length=2)),
                ('image', models.CharField(blank=True, default=None, max_length=2048, null=True)),
                ('portionable', models.BooleanField(blank=True, default=False)),
                ('portion_weight', models.IntegerField(blank=True, default=None, null=True)),
                ('portion_weight_format', models.CharField(blank=True, choices=[('g', 'Grams'), ('Kg', 'Kilograms'), ('mL', 'Millilitre'), ('L', 'Litre')], default='g', max_length=2, null=True)),
                ('consume_within_x_days_of_opening', models.IntegerField(blank=True, default=None, null=True)),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='store_cupboard.brand')),
            ],
            options={
                'verbose_name': 'Item Detail',
                'verbose_name_plural': 'Item Details',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened', models.BooleanField(blank=True, default=False)),
                ('opened_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('consumed', models.BooleanField(blank=True, default=False)),
                ('consumption_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('consumed_by_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='consumed_by', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='store_cupboard.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='store_cupboard.item')),
                ('opened_by_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='opened_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='manufacturer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='store_cupboard.manufacturer'),
        ),
    ]
