# Generated by Django 3.1 on 2020-08-20 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_cupboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(verbose_name='date purchased')),
                ('opened_date', models.DateTimeField(verbose_name='date opened')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_cupboard.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_weight', models.CharField(max_length=6)),
                ('consume_by_date', models.DateTimeField(verbose_name='date to be consumed by')),
                ('expiration_date', models.DateTimeField(verbose_name='date expires')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_cupboard.item')),
            ],
        ),
        migrations.DeleteModel(
            name='CleaningInventory',
        ),
        migrations.DeleteModel(
            name='FoodInventory',
        ),
    ]
