# Generated by Django 3.1 on 2020-08-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_cupboard', '0002_auto_20200820_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmetadata',
            name='consume_by_date',
        ),
        migrations.AddField(
            model_name='itemmetadata',
            name='consume_within_days',
            field=models.IntegerField(default=0),
        ),
    ]
