# Generated by Django 3.1 on 2020-08-20 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_cupboard', '0003_auto_20200820_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_cupboard.inventory'),
        ),
        migrations.AlterField(
            model_name='itemmetadata',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_cupboard.item'),
        ),
    ]
