# Generated by Django 3.1 on 2020-08-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_cupboard', '0004_auto_20200820_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='inventory',
        ),
    ]
