# Generated by Django 3.1 on 2020-08-20 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store_cupboard', '0005_auto_20200820_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='opened_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_text',
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='consume_within_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 19, 8, 54, 585310, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='item_portion_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='item_total_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='item_weight_format',
            field=models.CharField(default='g', max_length=6),
        ),
        migrations.AddField(
            model_name='item',
            name='opened_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 19, 8, 54, 585310, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 19, 8, 54, 585310, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ItemMetaData',
        ),
    ]
